//! Compact, transport-independent control protocol for product-facing tools.
//!
//! Frames are deliberately bounded to less than one USB full-speed bulk
//! packet. The protocol carries typed integer values; human-readable text is
//! generated by the host application rather than stored in MCU flash.

use crate::capabilities::{CapabilitiesKind, PdoValidity, SourceCapabilities, SupplyKind};
use crate::command::Command;
use crate::controller::{ControllerError, UserRequest};
use crate::request::{
    CurrentConfidence, Demand, LimitReason, PlanError, PlannedOperating, PlannedVoltage, Preference, RequestMessage,
    RequestPlan,
};
use crate::runtime::{HardResetCause, HardResetDirection, RequestResult};
use crate::status::{PpsStatus, SourceAlert, SourceStatus, StatusQuery, StatusQueryFailure};
use crate::units::{Milliamps, Millivolts, Milliwatts};

pub const CONTROL_PROTOCOL_VERSION: u8 = 1;
pub const FRAME_MAGIC: [u8; 2] = *b"PD";
pub const MAX_FRAME_LEN: usize = 63;
pub const MAX_PAYLOAD_LEN: usize = MAX_FRAME_LEN - 7;
const FRAME_PREFIX_LEN: usize = 6;
const NONE_U32: u32 = u32::MAX;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum CommandKind {
    Device = 0x01,
    Capabilities = 0x02,
    Plans = 0x03,
    SourceInfo = 0x04,
    EnterEpr = 0x05,
    EprCapabilities = 0x06,
    ExitEpr = 0x07,
    Status = 0x08,
    Help = 0x09,
    SourceStatus = 0x0a,
    PpsStatus = 0x0b,
    RequestVoltage = 0x10,
    RequestPdo = 0x11,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum EventKind {
    CommandResult = 0x80,
    Device = 0x81,
    Lifecycle = 0x82,
    Capabilities = 0x83,
    Plan = 0x84,
    ControllerError = 0x85,
    SourceInfo = 0x86,
    RequestResult = 0x87,
    HardReset = 0x88,
    Epr = 0x89,
    CapabilityPlansStarted = 0x8a,
    CapabilityPlanUnavailable = 0x8b,
    IntegrationError = 0x8c,
    Help = 0x8d,
    SourceAlert = 0x8e,
    SourceStatus = 0x8f,
    PpsStatus = 0x90,
    StatusQueryFailed = 0x91,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum CommandStatus {
    Queued = 0,
    Busy = 1,
    Invalid = 2,
    Unsupported = 3,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum LifecycleEvent {
    UsbReady = 0,
    CcDetected = 1,
    Attached = 2,
    SinkTxAllowed = 3,
    SinkTxDeferred = 4,
    PdStopped = 5,
    PdStoppedDetach = 6,
    PdStoppedPhy = 7,
    PdStoppedTimeout = 8,
    PdStoppedProtocol = 9,
    PdStoppedPolicy = 10,
    PdResetFailed = 11,
    Detached = 12,
    ProtocolLost = 13,
    HardResetRecoveryComplete = 14,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum PlanStage {
    Preview = 0,
    Requesting = 1,
    Contract = 2,
    Refreshed = 3,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum EprEvent {
    EntryFailed = 0,
    DiscoveryStarted = 1,
    DiscoveryUnavailable = 2,
    AutomaticDiscoveryDisabled = 3,
    ManualEntryStarted = 4,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum IntegrationError {
    CapabilitiesRejected = 0,
    RequestRejected = 1,
    CapabilityPlansUnavailable = 2,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct DeviceInfo {
    pub uid: [u8; 8],
    pub flags: u8,
    pub max_voltage: Millivolts,
    pub max_current: Milliamps,
    pub max_power: Milliwatts,
}

impl DeviceInfo {
    pub const PPS_SUPPORTED: u8 = 1 << 0;
    pub const EPR_SUPPORTED: u8 = 1 << 1;
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ControlEvent {
    CommandResult(CommandStatus),
    Device(DeviceInfo),
    Lifecycle { event: LifecycleEvent, detail: u32, extra: u32 },
    Capabilities(SourceCapabilities),
    Plan { stage: PlanStage, plan: Option<RequestPlan> },
    ControllerError(ControllerError),
    SourceInfo { present_watts: u8, maximum_watts: u8, reported_watts: u8 },
    SourceAlert(SourceAlert),
    SourceStatus(SourceStatus),
    PpsStatus(PpsStatus),
    StatusQueryFailed { query: StatusQuery, failure: StatusQueryFailure },
    RequestResult(RequestResult),
    HardReset { direction: HardResetDirection, cause: HardResetCause, recovery_ms: u32 },
    Epr { event: EprEvent, detail: u8, extra: u8 },
    CapabilityPlansStarted { count: u8 },
    CapabilityPlanUnavailable { position: u8, validity: PdoValidity },
    IntegrationError(IntegrationError),
    Help,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ControlFrame {
    pub version: u8,
    pub kind: u8,
    pub sequence: u8,
    payload: [u8; MAX_PAYLOAD_LEN],
    payload_len: u8,
}

impl ControlFrame {
    pub fn payload(&self) -> &[u8] {
        &self.payload[..usize::from(self.payload_len)]
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FrameError {
    PayloadTooLong,
    OutputTooSmall,
    InvalidLength,
    InvalidChecksum,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CommandDecodeError {
    UnsupportedVersion,
    UnknownCommand,
    InvalidLength,
    InvalidValue,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct DecodedCommand {
    pub sequence: u8,
    pub command: Command,
}

#[derive(Clone, Copy, Debug)]
pub struct FrameDecoder {
    bytes: [u8; MAX_FRAME_LEN],
    len: u8,
    expected_len: u8,
}

impl Default for FrameDecoder {
    fn default() -> Self {
        Self::new()
    }
}

impl FrameDecoder {
    pub const fn new() -> Self {
        Self { bytes: [0; MAX_FRAME_LEN], len: 0, expected_len: 0 }
    }

    pub fn reset(&mut self) {
        self.len = 0;
        self.expected_len = 0;
    }

    pub fn push(&mut self, byte: u8) -> Option<Result<ControlFrame, FrameError>> {
        match self.len {
            0 => {
                if byte == FRAME_MAGIC[0] {
                    self.bytes[0] = byte;
                    self.len = 1;
                }
                return None;
            }
            1 => {
                if byte == FRAME_MAGIC[1] {
                    self.bytes[1] = byte;
                    self.len = 2;
                } else if byte == FRAME_MAGIC[0] {
                    self.bytes[0] = byte;
                } else {
                    self.reset();
                }
                return None;
            }
            _ => {}
        }

        let index = usize::from(self.len);
        if index >= self.bytes.len() {
            self.reset();
            return Some(Err(FrameError::InvalidLength));
        }
        self.bytes[index] = byte;
        self.len += 1;

        if usize::from(self.len) == FRAME_PREFIX_LEN {
            let payload_len = usize::from(self.bytes[5]);
            if payload_len > MAX_PAYLOAD_LEN {
                self.reset();
                return Some(Err(FrameError::InvalidLength));
            }
            self.expected_len = (FRAME_PREFIX_LEN + payload_len + 1) as u8;
        }

        if self.expected_len == 0 || self.len < self.expected_len {
            return None;
        }

        let frame_len = usize::from(self.expected_len);
        let supplied_checksum = self.bytes[frame_len - 1];
        let expected_checksum = checksum(&self.bytes[2..frame_len - 1]);
        if supplied_checksum != expected_checksum {
            self.reset();
            return Some(Err(FrameError::InvalidChecksum));
        }

        let payload_len = usize::from(self.bytes[5]);
        let mut payload = [0; MAX_PAYLOAD_LEN];
        payload[..payload_len].copy_from_slice(&self.bytes[FRAME_PREFIX_LEN..FRAME_PREFIX_LEN + payload_len]);
        let frame = ControlFrame {
            version: self.bytes[2],
            kind: self.bytes[3],
            sequence: self.bytes[4],
            payload,
            payload_len: payload_len as u8,
        };
        self.reset();
        Some(Ok(frame))
    }
}

pub fn encode_frame(
    version: u8,
    kind: u8,
    sequence: u8,
    payload: &[u8],
    output: &mut [u8],
) -> Result<usize, FrameError> {
    if payload.len() > MAX_PAYLOAD_LEN {
        return Err(FrameError::PayloadTooLong);
    }
    let frame_len = FRAME_PREFIX_LEN + payload.len() + 1;
    if output.len() < frame_len {
        return Err(FrameError::OutputTooSmall);
    }

    output[0..2].copy_from_slice(&FRAME_MAGIC);
    output[2] = version;
    output[3] = kind;
    output[4] = sequence;
    output[5] = payload.len() as u8;
    output[FRAME_PREFIX_LEN..FRAME_PREFIX_LEN + payload.len()].copy_from_slice(payload);
    output[frame_len - 1] = checksum(&output[2..frame_len - 1]);
    Ok(frame_len)
}

pub fn decode_command(frame: &ControlFrame) -> Result<DecodedCommand, CommandDecodeError> {
    if frame.version != CONTROL_PROTOCOL_VERSION {
        return Err(CommandDecodeError::UnsupportedVersion);
    }

    let payload = frame.payload();
    let command = match frame.kind {
        kind if kind == CommandKind::Device as u8 => no_payload(payload, Command::Identity)?,
        kind if kind == CommandKind::Capabilities as u8 => no_payload(payload, Command::Capabilities)?,
        kind if kind == CommandKind::Plans as u8 => no_payload(payload, Command::Plans)?,
        kind if kind == CommandKind::SourceInfo as u8 => no_payload(payload, Command::RequestSourceInfo)?,
        kind if kind == CommandKind::EnterEpr as u8 => no_payload(payload, Command::EnterEpr)?,
        kind if kind == CommandKind::EprCapabilities as u8 => no_payload(payload, Command::RequestEprCapabilities)?,
        kind if kind == CommandKind::ExitEpr as u8 => no_payload(payload, Command::ExitEpr)?,
        kind if kind == CommandKind::Status as u8 => no_payload(payload, Command::Status)?,
        kind if kind == CommandKind::Help as u8 => no_payload(payload, Command::Help)?,
        kind if kind == CommandKind::SourceStatus as u8 => no_payload(payload, Command::RequestSourceStatus)?,
        kind if kind == CommandKind::PpsStatus as u8 => no_payload(payload, Command::RequestPpsStatus)?,
        kind if kind == CommandKind::RequestVoltage as u8 => decode_voltage_request(payload)?,
        kind if kind == CommandKind::RequestPdo as u8 => decode_pdo_request(payload)?,
        _ => return Err(CommandDecodeError::UnknownCommand),
    };
    Ok(DecodedCommand { sequence: frame.sequence, command })
}

pub fn encode_event(event: ControlEvent, sequence: u8, output: &mut [u8]) -> Result<usize, FrameError> {
    let mut payload = [0; MAX_PAYLOAD_LEN];
    let mut writer = PayloadWriter::new(&mut payload);
    let kind = match event {
        ControlEvent::CommandResult(status) => {
            writer.u8(status as u8)?;
            EventKind::CommandResult
        }
        ControlEvent::Device(info) => {
            writer.bytes(&info.uid)?;
            writer.u8(info.flags)?;
            writer.u32(info.max_voltage.get())?;
            writer.u32(info.max_current.get())?;
            writer.u32(info.max_power.get())?;
            EventKind::Device
        }
        ControlEvent::Lifecycle { event, detail, extra } => {
            writer.u8(event as u8)?;
            writer.u32(detail)?;
            writer.u32(extra)?;
            EventKind::Lifecycle
        }
        ControlEvent::Capabilities(capabilities) => {
            writer.u8(capabilities_kind(capabilities.kind()))?;
            writer.u8(u8::from(capabilities.epr_mode_capable()))?;
            writer.u8(capabilities.len() as u8)?;
            for &pdo in capabilities.raw_pdos() {
                writer.u32(pdo)?;
            }
            EventKind::Capabilities
        }
        ControlEvent::Plan { stage, plan } => {
            writer.u8(stage as u8)?;
            writer.u8(u8::from(plan.is_some()))?;
            if let Some(plan) = plan {
                encode_plan(plan, &mut writer)?;
            }
            EventKind::Plan
        }
        ControlEvent::ControllerError(error) => {
            let (code, detail, extra) = controller_error_fields(error);
            writer.u8(code)?;
            writer.u32(detail)?;
            writer.u32(extra)?;
            EventKind::ControllerError
        }
        ControlEvent::SourceInfo { present_watts, maximum_watts, reported_watts } => {
            writer.u8(present_watts)?;
            writer.u8(maximum_watts)?;
            writer.u8(reported_watts)?;
            EventKind::SourceInfo
        }
        ControlEvent::SourceAlert(alert) => {
            writer.u32(alert.raw())?;
            EventKind::SourceAlert
        }
        ControlEvent::SourceStatus(status) => {
            writer.u8(u8::from(status.pps_mode_valid()))?;
            writer.bytes(&status.raw_bytes())?;
            EventKind::SourceStatus
        }
        ControlEvent::PpsStatus(status) => {
            writer.bytes(&status.raw_bytes())?;
            EventKind::PpsStatus
        }
        ControlEvent::StatusQueryFailed { query, failure } => {
            writer.u8(match query {
                StatusQuery::General => 0,
                StatusQuery::Pps => 1,
            })?;
            writer.u8(match failure {
                StatusQueryFailure::NotSupported => 0,
                StatusQueryFailure::Rejected => 1,
                StatusQueryFailure::Deferred => 2,
                StatusQueryFailure::Timeout => 3,
            })?;
            EventKind::StatusQueryFailed
        }
        ControlEvent::RequestResult(result) => {
            writer.u8(match result {
                RequestResult::Rejected => 0,
                RequestResult::Deferred => 1,
            })?;
            EventKind::RequestResult
        }
        ControlEvent::HardReset { direction, cause, recovery_ms } => {
            writer.u8(match direction {
                HardResetDirection::Received => 0,
                HardResetDirection::Sent => 1,
            })?;
            writer.u32(recovery_ms)?;
            writer.u8(cause as u8)?;
            EventKind::HardReset
        }
        ControlEvent::Epr { event, detail, extra } => {
            writer.u8(event as u8)?;
            writer.u8(detail)?;
            writer.u8(extra)?;
            EventKind::Epr
        }
        ControlEvent::CapabilityPlansStarted { count } => {
            writer.u8(count)?;
            EventKind::CapabilityPlansStarted
        }
        ControlEvent::CapabilityPlanUnavailable { position, validity } => {
            writer.u8(position)?;
            writer.u8(validity_code(validity))?;
            EventKind::CapabilityPlanUnavailable
        }
        ControlEvent::IntegrationError(error) => {
            writer.u8(error as u8)?;
            EventKind::IntegrationError
        }
        ControlEvent::Help => EventKind::Help,
    };

    encode_frame(CONTROL_PROTOCOL_VERSION, kind as u8, sequence, writer.written(), output)
}

fn no_payload(payload: &[u8], command: Command) -> Result<Command, CommandDecodeError> {
    if payload.is_empty() {
        Ok(command)
    } else {
        Err(CommandDecodeError::InvalidLength)
    }
}

fn decode_voltage_request(payload: &[u8]) -> Result<Command, CommandDecodeError> {
    if payload.len() != 9 {
        return Err(CommandDecodeError::InvalidLength);
    }
    let voltage = read_u32(payload, 0)?;
    let current = optional_u32(read_u32(payload, 4)?);
    let preference = match payload[8] {
        0 => Preference::Auto,
        1 => Preference::Fixed,
        2 => Preference::Pps,
        3 => Preference::SprAvs,
        4 => Preference::EprAvs,
        5 => Preference::EprAvsNonstandard,
        _ => return Err(CommandDecodeError::InvalidValue),
    };
    if voltage == 0 || current == Some(0) {
        return Err(CommandDecodeError::InvalidValue);
    }
    Ok(Command::Request(UserRequest::Voltage {
        voltage: Millivolts(voltage),
        current: current.map(Milliamps),
        preference,
    }))
}

fn decode_pdo_request(payload: &[u8]) -> Result<Command, CommandDecodeError> {
    if payload.len() != 10 {
        return Err(CommandDecodeError::InvalidLength);
    }
    let position = payload[0];
    if position == 0 {
        return Err(CommandDecodeError::InvalidValue);
    }
    let voltage = read_u32(payload, 2)?;
    let current = optional_u32(read_u32(payload, 6)?);
    let demand = match payload[1] {
        0 => Demand::Maximum,
        1 => Demand::Current(Milliamps(current.ok_or(CommandDecodeError::InvalidValue)?)),
        2 if voltage != 0 => Demand::Adjustable { voltage: Millivolts(voltage), current: current.map(Milliamps) },
        _ => return Err(CommandDecodeError::InvalidValue),
    };
    if matches!(demand, Demand::Current(Milliamps(0))) || current == Some(0) {
        return Err(CommandDecodeError::InvalidValue);
    }
    Ok(Command::Request(UserRequest::Pdo { position, demand }))
}

fn read_u32(payload: &[u8], offset: usize) -> Result<u32, CommandDecodeError> {
    let bytes = payload.get(offset..offset + 4).ok_or(CommandDecodeError::InvalidLength)?;
    Ok(u32::from_le_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]))
}

fn optional_u32(value: u32) -> Option<u32> {
    (value != NONE_U32).then_some(value)
}

fn encode_plan(plan: RequestPlan, writer: &mut PayloadWriter<'_>) -> Result<(), FrameError> {
    writer.u8(plan.object_position)?;
    writer.u8(supply_kind(plan.supply))?;
    let mut flags = 0;
    if matches!(plan.message, RequestMessage::EprRequest) {
        flags |= 1 << 0;
    }
    if plan.capability_mismatch {
        flags |= 1 << 1;
    }
    writer.u8(flags)?;

    match plan.voltage {
        PlannedVoltage::Fixed(voltage) => {
            writer.u8(0)?;
            writer.u32(voltage.get())?;
            writer.u32(voltage.get())?;
            writer.u16(0)?;
        }
        PlannedVoltage::Adjustable { requested, encoded, step_mv } => {
            writer.u8(1)?;
            writer.u32(requested.get())?;
            writer.u32(encoded.get())?;
            writer.u16(step_mv)?;
        }
    }

    match plan.operating {
        PlannedOperating::Current { requested, source_limit, operating, confidence, limited_by } => {
            writer.u32(requested.map_or(NONE_U32, Milliamps::get))?;
            writer.u32(source_limit.get())?;
            writer.u32(operating.get())?;
            writer.u8(confidence_code(confidence))?;
            writer.u8(limit_code(limited_by))?;
        }
    }
    writer.u32(plan.rdo)?;
    writer.u32(plan.pdo_copy.unwrap_or(0))?;
    Ok(())
}

fn controller_error_fields(error: ControllerError) -> (u8, u32, u32) {
    match error {
        ControllerError::NoCapabilities(kind) => (0, u32::from(capabilities_kind(kind)), 0),
        ControllerError::Busy(state) => (1, state as u32, 0),
        ControllerError::EprUnavailable => (2, 0, 0),
        ControllerError::EprNotConfigured => (3, 0, 0),
        ControllerError::InvalidEprOperationalPdp(pdp) => (4, pdp.get(), 0),
        ControllerError::NotInEprMode => (5, 0, 0),
        ControllerError::Plan(plan) => match plan {
            PlanError::PositionUnavailable(position) => (16, u32::from(position), 0),
            PlanError::MalformedPdo { position, .. } => (17, u32::from(position), 0),
            PlanError::UnsupportedPdo(position) => (18, u32::from(position), 0),
            PlanError::InvalidDemand { position, supply } => (19, u32::from(position), u32::from(supply_kind(supply))),
            PlanError::VoltageUnavailable(voltage) => (20, voltage.get(), 0),
            PlanError::VoltageOutsideOffer { position, requested } => (21, u32::from(position), requested.get()),
            PlanError::VoltageAboveSinkLimit { requested, maximum } => (22, requested.get(), maximum.get()),
            PlanError::CapabilitiesModeMismatch => (23, 0, 0),
            PlanError::EprModeRequired(position) => (24, u32::from(position), 0),
            PlanError::ZeroOperatingValue => (25, 0, 0),
        },
    }
}

fn capabilities_kind(kind: CapabilitiesKind) -> u8 {
    match kind {
        CapabilitiesKind::Spr => 0,
        CapabilitiesKind::Epr => 1,
    }
}

fn supply_kind(kind: SupplyKind) -> u8 {
    match kind {
        SupplyKind::Fixed => 0,
        SupplyKind::Pps => 1,
        SupplyKind::SprAvs => 2,
        SupplyKind::EprAvs => 3,
        SupplyKind::ZeroPadding => 4,
        SupplyKind::Unsupported => 5,
    }
}

fn validity_code(validity: PdoValidity) -> u8 {
    match validity {
        PdoValidity::Valid => 0,
        PdoValidity::Compatible => 1,
        PdoValidity::ZeroPadding => 2,
        PdoValidity::Malformed(_) => 3,
        PdoValidity::Unsupported => 4,
    }
}

fn confidence_code(confidence: CurrentConfidence) -> u8 {
    match confidence {
        CurrentConfidence::Advertised => 0,
        CurrentConfidence::DerivedFromPdoPdp => 1,
        CurrentConfidence::DerivedFromSourceInfo => 2,
        CurrentConfidence::PowerLimitedUpperBound => 3,
    }
}

fn limit_code(limit: LimitReason) -> u8 {
    match limit {
        LimitReason::Source => 0,
        LimitReason::Protocol => 1,
        LimitReason::Board => 2,
        LimitReason::Cable => 3,
        LimitReason::SinkPower => 4,
        LimitReason::User => 5,
    }
}

fn checksum(bytes: &[u8]) -> u8 {
    let mut crc = 0;
    for &byte in bytes {
        crc ^= byte;
        for _ in 0..8 {
            crc = if crc & 0x80 != 0 { (crc << 1) ^ 0x07 } else { crc << 1 };
        }
    }
    crc
}

struct PayloadWriter<'a> {
    output: &'a mut [u8],
    len: usize,
}

impl<'a> PayloadWriter<'a> {
    fn new(output: &'a mut [u8]) -> Self {
        Self { output, len: 0 }
    }

    fn written(&self) -> &[u8] {
        &self.output[..self.len]
    }

    fn bytes(&mut self, value: &[u8]) -> Result<(), FrameError> {
        let end = self.len.checked_add(value.len()).ok_or(FrameError::PayloadTooLong)?;
        let destination = self.output.get_mut(self.len..end).ok_or(FrameError::PayloadTooLong)?;
        destination.copy_from_slice(value);
        self.len = end;
        Ok(())
    }

    fn u8(&mut self, value: u8) -> Result<(), FrameError> {
        self.bytes(&[value])
    }

    fn u16(&mut self, value: u16) -> Result<(), FrameError> {
        self.bytes(&value.to_le_bytes())
    }

    fn u32(&mut self, value: u32) -> Result<(), FrameError> {
        self.bytes(&value.to_le_bytes())
    }
}
