[package]
name = "ch32x035-usb-pd-epr-sink-protocol-tests"
version.workspace = true
edition = "2024"
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
pd-sink = { package = "ch32x035-usb-pd-epr-sink", path = "../../crates/pd-sink" }
usbpd = { path = "../../vendor/usbpd", features = ["hard-reset-reasons"] }
usbpd-traits = { path = "../../vendor/usbpd-traits" }
