[package]
name = "ch32x035-usb-pd-epr-sink-reference"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[features]
default = ["sdi-log", "ch32x035f8u6"]
ch32x035c8t6 = ["pd-sink/ch32x035c8t6", "ch32-hal/ch32x035c8t6"]
ch32x035f7p6 = ["pd-sink/ch32x035f7p6", "ch32-hal/ch32x035f7p6"]
ch32x035f8u6 = ["pd-sink/ch32x035f8u6", "ch32-hal/ch32x035f8u6"]
ch32x035g8r6 = ["pd-sink/ch32x035g8r6", "ch32-hal/ch32x035g8r6"]
ch32x035g8u6 = ["pd-sink/ch32x035g8u6", "ch32-hal/ch32x035g8u6"]
ch32x035r8t6 = ["pd-sink/ch32x035r8t6", "ch32-hal/ch32x035r8t6"]
sdi-log = []
usb-control = ["pd-sink/hard-reset-reasons"]
dev-text-console = []
output-default-off = []
rev0-validation = []
pps-capable-hardware = []
epr-capable-hardware = []
epr-50v-compatible-hardware = ["epr-capable-hardware"]

[dependencies]
pd-sink = { package = "ch32x035-usb-pd-epr-sink", path = "../../crates/pd-sink", default-features = false }
ch32-hal = { path = "../../vendor/ch32-hal", default-features = false, features = [
    "memory-x",
    "embassy",
    "exti",
    "rt",
    "time-driver-tim2",
] }
embassy-executor = { version = "0.10.0", features = ["platform-spin", "executor-thread"] }
embassy-futures = "0.1.2"
embassy-sync = "0.8.0"
embassy-time = "0.5.1"
panic-halt = "1.0"
qingke = "0.7"
qingke-rt = "0.7"
