MEMORY
{
  /* Reserve the final two 256-byte user-flash pages (0xF600 and 0xF700)
     for the power-loss-safe PD black-box A/B journal. */
  FLASH : ORIGIN = 0x00000000, LENGTH = 0xF600
  RAM : ORIGIN = 0x20000000, LENGTH = 20K
}

REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);
